### ISSUE TITLE
Errors compiling example with XCode 8 and workarounds

### ISSUE THREAD

**Issue by miniBloq** [google/blockly-ios#266]
I followed the steps on this page https://developers.google.com/blockly/guides/get-started/ios to install Blockly in XCode 8.2 Beta using Carthage, and a few errors appeared. I found the solutions, so I wanted to document them somewhere. Please feel free to move this "issue" to any place you may considere better:

1. The following line does not compile. 

`blockFactory.load(fromDefaultFiles: .allDefault)`

**Solution:** Change "allDefault" to "AllDefault"

`blockFactory.load(fromDefaultFiles: .AllDefault)`

2. There was a runtime error when running the program ("dyld: Library not loaded:...").

**Solution:** Follow step 4 for iOS building, documented in Carthage's GitHub page: https://github.com/Carthage/Carthage
That means adding the "Build Phases" script, with the following inputs:

Shell: `/bin/sh`
[Commands]: `/usr/local/bin/carthage copy-frameworks`
Input Files:
`$(SRCROOT)/Carthage/Build/iOS/AEXML.framework`
`$(SRCROOT)/Carthage/Build/iOS/Blockly.framework`

**Comment by vicng** [comment]
Thanks for flagging these issues.

1) Our soon to be released v0.5.1 actually uses `.allDefault` instead of `.AllDefault`.

This was a problem with our documentation being out-of-sync with the latest release. We recently made a change to our development process to address this issue (the "master" branch will be synced to the latest release, while the "develop" branch will contain the freshest code). Hopefully you don't run into this going forward.

2) We'll update the documentation, thanks!
