### ISSUE TITLE
set the text color for message 

### ISSUE THREAD

**Issue by cartmanguo** [google/blockly-ios#335]
is there a property to set the text color for message displayed on the block?
the default color is black,but in the Android version and web version,the default message text color is white

**Comment by CoryDCode** [comment]
Not at the moment, but it should be a simple fix - I'll put a pull request together shortly.

**Comment by CoryDCode** [comment]
Sorry about the delay, but this has been fixed in #336. You can change the text color on LayoutConfig with the new FieldLabelTextColor and FieldEditableTextColor properties. See https://developers.google.com/blockly/guides/configure/ios/customize-blockly-editor for more information.

Note - We didn't change the default colors for now, since we'll have to change the color of all of our default blocks before we do that, but it's configurable now.
