### ISSUE TITLE
Support for parallel programs

### ISSUE THREAD

**Issue by elcocui** [google/blockly-ios#340]
I'm trying to use iOS blockly for parallel processing but am unable to find the right method for implementation in my iOS app. Blockly documentation at  https://developers.google.com/blockly/guides/create-custom-blocks/block-paradigms  suggests a method for web apps but is there an alternative for iOS-blockly?
Many thanks

**Comment by vicng** [comment]
Here's the code generator documentation for iOS:
https://developers.google.com/blockly/guides/configure/ios/code-generators

Is this what you're looking for?

**Comment by elcocui** [comment]
sorry.. updated. It was block-paradigm. Specifically  parallel programs

**Comment by elcocui** [comment]
I'm interested to know how I could generate and execute code for parallel block stacks instead of serially (as shown by sample app).

**Comment by vicng** [comment]
Due to memory issues with creating more than one web view in the background, the code generator service will only generate code for one workspace at a time. That said, it is a relatively inexpensive operation, so you could call it many times for multiple workspaces.

With that in mind, here's an approach to solve it, assuming you have some way to determine which block stacks need to be run in parallel (ie. all top-level blocks or blocks connected to a special "run" block?).

1) When you go to generate code, create a temporary Workspace object for each block stack.
2) From the main Workspace object, copy each block stack into its own Workspace object (and perhaps and dependency procedure blocks that need to be there too).
3) Generate code for each Workspace.

In terms of running the code in parallel, it depends on what language you're using to accomplish this. I believe you can run Javascript code on separate background threads and have it callback to iOS code (either through a WKWebView or JSContext). Then, you can sync up with the main thread to render anything.  The only worry I'd have is running into memory issues with multiple Javascript VMs. There may be a more efficient VM/interpreter out there for a code generator language we support (Lua maybe?).

I hope that answers your question.

**Comment by elcocui** [comment]
Thanks a lot. Your suggestions are a great place to start. I'll try to implement them and will let you know when I make progress.
