### ISSUE TITLE
Blockly Sample Application Memory Leaks

### ISSUE THREAD

**Issue by hatem93** [google/blockly-ios#373]
Hi, I have been having alot of trouble with memory leaks related to blockly i through that they where related to my application but the demo application provided here "BlocklySample" produce the same memory leaks

Here is an image of the momery leaks in the leaks insturment

<img width="1275" alt="screenshot at apr 23 22-57-24" src="https://cloud.githubusercontent.com/assets/10016580/25317398/41dda868-2878-11e7-8689-f4be2504a472.png">

Here is a link for the trace zip file
https://drive.google.com/open?id=0B7p-Y_jYkZ_0M0ZndUhtM1dITXM

I am using ios 8.0
on iPadAir Simulator
on mac os sierra version 10.12
on Xcode  8.3.2

Am i doing something wrong? or is that normal

**Comment by vicng** [comment]
Thanks for bringing up this issue.

Running it on my machine, I see leaks (filtered by "Blockly") and allocations that aren't being deallocated (filtered by "BKY").

It's something that I was planning on looking at in the ***very*** near future, along with performance optimization (I've been putting it on hold while building out a features over the last few months). So please hold tight -- they will be fixed shortly!

**Comment by hatem93** [comment]
thanks for the fast response looking forward to the fixes

**Comment by hatem93** [comment]
any updates?

**Comment by vicng** [comment]
Sorry, I have been busy/sidetracked for the last couple of weeks -- I will try to get a fix in this week.

**Comment by vicng** [comment]
FYI, pull request #388 now fixes the sources of major memory leakage.

However, there's still one source of minor leakage that I can't seem to solve, which is from "ContiguousArrayStorage<Field>" (ie. arrays being created for Field objects). I suspect that it's a bug in the iOS SDK or even in Instruments, as it only shows up for iOS 10 and not 8/9.

The good news is that these remaining leaks only seem to occur when first loading a workbench with new blocks and that the leaks are small in memory.

I'll keep my eye on this issue though, I'm hoping WWDC 17/iOS 11 may provide more insight into the problem. If you continue running into large memory issues, let us know.

**Comment by hatem93** [comment]
thanks alot will let you  know

**Comment by hatem93** [comment]
Sorry for the late response i have tried the new update, I am still having some leaks from blockly in my application and  in the blockly sample application provided, I am not sure wether i am doing something wrong or not.

here is an image from the instruments from blocksample application

<img width="1273" alt="screenshot at may 20 16-58-39" src="https://cloud.githubusercontent.com/assets/10016580/26279365/0127b0ee-3db2-11e7-9e40-f3d5d9e2d33d.png">

still using the same configuration as before 

i am now in the process of releasing my application on apple store do you know wether the memory leaks issue will lead to a rejection from apple.

**Comment by vicng** [comment]
I don't think minor leaks will get you rejected by Apple (some of the iOS SDK leaks), but obviously it isn't a good sign if your app is leaking terribly.

When looking for leaks, it's more important to check for severity than existence. I usually check two things:
1) Cyclical references - Does memory not get de-allocated (eg. after say popping a view controller)? This is the most severe type of leak and you shouldn't submit if you have any of them. None of these exist in the Blockly library, so if this is happening, it's most likely part of your codebase. 
2) Leaks due to bad reference counting (the Memory Leaks Instrument) - I've found that these happen just from using certain parts of the iOS SDK. It's hard to generate your own now with ARC so it's mostly making sure that you aren't calling those leaky parts too often (eg. you can see there's something leaky with NSNumberFormatter, which Blockly uses).

Lastly, make sure you're enabling "whole-module-optimization" when building for release. This will improve performance of your app and it may eliminate some of these leaks you have been seeing.

Hopefully this answers your questions.

If you have 5 minutes, please fill out our [dev questionnaire](https://developers.google.com/blockly/registration) too -- it really helps us out figure out how to cater to our devs.

Good luck on your submission!

**Comment by hatem93** [comment]
Thanks alot for the advices and the continous support
